[2024-01-21T11:36:08.074-0800] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: executing_sql_pipeline.insert_values_2 manual__2024-01-21T19:35:59.630505+00:00 [queued]>
[2024-01-21T11:36:08.088-0800] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: executing_sql_pipeline.insert_values_2 manual__2024-01-21T19:35:59.630505+00:00 [queued]>
[2024-01-21T11:36:08.088-0800] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2024-01-21T11:36:08.088-0800] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2024-01-21T11:36:08.088-0800] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2024-01-21T11:36:08.129-0800] {taskinstance.py:1309} INFO - Executing <Task(SqliteOperator): insert_values_2> on 2024-01-21 19:35:59.630505+00:00
[2024-01-21T11:36:08.136-0800] {standard_task_runner.py:55} INFO - Started process 30754 to run task
[2024-01-21T11:36:08.141-0800] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'executing_sql_pipeline', 'insert_values_2', 'manual__2024-01-21T19:35:59.630505+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/executing_sql_pipeline.py', '--cfg-path', '/tmp/tmp0be94e9s']
[2024-01-21T11:36:08.143-0800] {standard_task_runner.py:83} INFO - Job 91: Subtask insert_values_2
[2024-01-21T11:36:08.221-0800] {task_command.py:389} INFO - Running <TaskInstance: executing_sql_pipeline.insert_values_2 manual__2024-01-21T19:35:59.630505+00:00 [running]> on host Mittu.
[2024-01-21T11:36:08.312-0800] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=madhu
AIRFLOW_CTX_DAG_ID=executing_sql_pipeline
AIRFLOW_CTX_TASK_ID=insert_values_2
AIRFLOW_CTX_EXECUTION_DATE=2024-01-21T19:35:59.630505+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-21T19:35:59.630505+00:00
[2024-01-21T11:36:08.312-0800] {sql.py:254} INFO - Executing: 
            INSERT INTO users (name, age) VALUES 
                ('Harry', 49),
                ('Nancy', 52),
                ('Elvis', 26),
                ('Mia', 20);
        
[2024-01-21T11:36:08.318-0800] {base.py:73} INFO - Using connection ID 'my_sqlite_conn' for task execution.
[2024-01-21T11:36:08.444-0800] {base.py:73} INFO - Using connection ID 'my_sqlite_conn' for task execution.
[2024-01-21T11:36:08.444-0800] {sql.py:375} INFO - Running statement: 
            INSERT INTO users (name, age) VALUES 
                ('Harry', 49),
                ('Nancy', 52),
                ('Elvis', 26),
                ('Mia', 20);
        , parameters: None
[2024-01-21T11:36:08.445-0800] {sql.py:384} INFO - Rows affected: 4
[2024-01-21T11:36:08.464-0800] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=executing_sql_pipeline, task_id=insert_values_2, execution_date=20240121T193559, start_date=20240121T193608, end_date=20240121T193608
[2024-01-21T11:36:08.556-0800] {local_task_job.py:212} INFO - Task exited with return code 0
[2024-01-21T11:36:08.584-0800] {taskinstance.py:2596} INFO - 1 downstream tasks scheduled from follow-on schedule check
