[2024-01-21T11:55:59.972-0800] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cron_catchup_backfill.taskChoose manual__2024-01-21T19:55:46.276773+00:00 [queued]>
[2024-01-21T11:55:59.988-0800] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cron_catchup_backfill.taskChoose manual__2024-01-21T19:55:46.276773+00:00 [queued]>
[2024-01-21T11:55:59.988-0800] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2024-01-21T11:55:59.988-0800] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2024-01-21T11:55:59.988-0800] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2024-01-21T11:56:00.022-0800] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): taskChoose> on 2024-01-21 19:55:46.276773+00:00
[2024-01-21T11:56:00.029-0800] {standard_task_runner.py:55} INFO - Started process 437 to run task
[2024-01-21T11:56:00.035-0800] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'cron_catchup_backfill', 'taskChoose', 'manual__2024-01-21T19:55:46.276773+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/executing_cron_catchup_backfill.py', '--cfg-path', '/tmp/tmpzzsldyc_']
[2024-01-21T11:56:00.037-0800] {standard_task_runner.py:83} INFO - Job 99: Subtask taskChoose
[2024-01-21T11:56:00.107-0800] {task_command.py:389} INFO - Running <TaskInstance: cron_catchup_backfill.taskChoose manual__2024-01-21T19:55:46.276773+00:00 [running]> on host Mittu.
[2024-01-21T11:56:00.194-0800] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=madhu
AIRFLOW_CTX_DAG_ID=cron_catchup_backfill
AIRFLOW_CTX_TASK_ID=taskChoose
AIRFLOW_CTX_EXECUTION_DATE=2024-01-21T19:55:46.276773+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-21T19:55:46.276773+00:00
[2024-01-21T11:56:00.195-0800] {python.py:177} INFO - Done. Returned value was: False
[2024-01-21T11:56:00.254-0800] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=cron_catchup_backfill, task_id=taskChoose, execution_date=20240121T195546, start_date=20240121T195559, end_date=20240121T195600
[2024-01-21T11:56:00.288-0800] {local_task_job.py:212} INFO - Task exited with return code 0
[2024-01-21T11:56:00.314-0800] {taskinstance.py:2596} INFO - 1 downstream tasks scheduled from follow-on schedule check
