[2024-01-21T11:35:11.993-0800] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: executing_sql_pipeline.insert_values_1 manual__2024-01-21T19:35:07.934519+00:00 [queued]>
[2024-01-21T11:35:12.001-0800] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: executing_sql_pipeline.insert_values_1 manual__2024-01-21T19:35:07.934519+00:00 [queued]>
[2024-01-21T11:35:12.001-0800] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2024-01-21T11:35:12.001-0800] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2024-01-21T11:35:12.001-0800] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2024-01-21T11:35:12.023-0800] {taskinstance.py:1309} INFO - Executing <Task(SqliteOperator): insert_values_1> on 2024-01-21 19:35:07.934519+00:00
[2024-01-21T11:35:12.029-0800] {standard_task_runner.py:55} INFO - Started process 30599 to run task
[2024-01-21T11:35:12.045-0800] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'executing_sql_pipeline', 'insert_values_1', 'manual__2024-01-21T19:35:07.934519+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/executing_sql_pipeline.py', '--cfg-path', '/tmp/tmpb0nxrvgt']
[2024-01-21T11:35:12.046-0800] {standard_task_runner.py:83} INFO - Job 84: Subtask insert_values_1
[2024-01-21T11:35:12.093-0800] {task_command.py:389} INFO - Running <TaskInstance: executing_sql_pipeline.insert_values_1 manual__2024-01-21T19:35:07.934519+00:00 [running]> on host Mittu.
[2024-01-21T11:35:12.155-0800] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=madhu
AIRFLOW_CTX_DAG_ID=executing_sql_pipeline
AIRFLOW_CTX_TASK_ID=insert_values_1
AIRFLOW_CTX_EXECUTION_DATE=2024-01-21T19:35:07.934519+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-21T19:35:07.934519+00:00
[2024-01-21T11:35:12.155-0800] {sql.py:254} INFO - Executing: 
        INSERT INTO users  (name, age , is_active) VALUES
                ('Julie', 30, false),
                ('Peter', 55, true),
                ('Emily', 37, false),
                ('Katrina', 54, false),
                ('Joseph', 27, true);
                
[2024-01-21T11:35:12.159-0800] {base.py:73} INFO - Using connection ID 'my_sqlite_conn' for task execution.
[2024-01-21T11:35:12.226-0800] {base.py:73} INFO - Using connection ID 'my_sqlite_conn' for task execution.
[2024-01-21T11:35:12.226-0800] {sql.py:375} INFO - Running statement: 
        INSERT INTO users  (name, age , is_active) VALUES
                ('Julie', 30, false),
                ('Peter', 55, true),
                ('Emily', 37, false),
                ('Katrina', 54, false),
                ('Joseph', 27, true);
                , parameters: None
[2024-01-21T11:35:12.227-0800] {sql.py:384} INFO - Rows affected: 5
[2024-01-21T11:35:12.242-0800] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=executing_sql_pipeline, task_id=insert_values_1, execution_date=20240121T193507, start_date=20240121T193511, end_date=20240121T193512
[2024-01-21T11:35:12.297-0800] {local_task_job.py:212} INFO - Task exited with return code 0
[2024-01-21T11:35:12.313-0800] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
