[2024-01-21T11:31:10.510-0800] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: executing_sql_pipeline.insert_values_1 manual__2024-01-21T19:31:05.770169+00:00 [queued]>
[2024-01-21T11:31:10.518-0800] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: executing_sql_pipeline.insert_values_1 manual__2024-01-21T19:31:05.770169+00:00 [queued]>
[2024-01-21T11:31:10.518-0800] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2024-01-21T11:31:10.518-0800] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2024-01-21T11:31:10.518-0800] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2024-01-21T11:31:10.538-0800] {taskinstance.py:1309} INFO - Executing <Task(SqliteOperator): insert_values_1> on 2024-01-21 19:31:05.770169+00:00
[2024-01-21T11:31:10.541-0800] {standard_task_runner.py:55} INFO - Started process 30168 to run task
[2024-01-21T11:31:10.544-0800] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'executing_sql_pipeline', 'insert_values_1', 'manual__2024-01-21T19:31:05.770169+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/executing_sql_pipeline.py', '--cfg-path', '/tmp/tmpg32dmcnh']
[2024-01-21T11:31:10.545-0800] {standard_task_runner.py:83} INFO - Job 80: Subtask insert_values_1
[2024-01-21T11:31:10.647-0800] {task_command.py:389} INFO - Running <TaskInstance: executing_sql_pipeline.insert_values_1 manual__2024-01-21T19:31:05.770169+00:00 [running]> on host Mittu.
[2024-01-21T11:31:10.764-0800] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=madhu
AIRFLOW_CTX_DAG_ID=executing_sql_pipeline
AIRFLOW_CTX_TASK_ID=insert_values_1
AIRFLOW_CTX_EXECUTION_DATE=2024-01-21T19:31:05.770169+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-21T19:31:05.770169+00:00
[2024-01-21T11:31:10.765-0800] {sql.py:254} INFO - Executing: 
        INSERT INTO users  (name, age , is_active) VALUES
                ('Julie', 30, false),
                ('Peter', 55, true),
                ('Emily', 37, false),
                ('Katrina', 54, false),
                ('Joseph', 27, true);
                
[2024-01-21T11:31:10.771-0800] {base.py:73} INFO - Using connection ID 'my_sqlite_conn' for task execution.
[2024-01-21T11:31:10.856-0800] {base.py:73} INFO - Using connection ID 'my_sqlite_conn' for task execution.
[2024-01-21T11:31:10.856-0800] {sql.py:375} INFO - Running statement: 
        INSERT INTO users  (name, age , is_active) VALUES
                ('Julie', 30, false),
                ('Peter', 55, true),
                ('Emily', 37, false),
                ('Katrina', 54, false),
                ('Joseph', 27, true);
                , parameters: None
[2024-01-21T11:31:10.857-0800] {sql.py:384} INFO - Rows affected: 5
[2024-01-21T11:31:10.877-0800] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=executing_sql_pipeline, task_id=insert_values_1, execution_date=20240121T193105, start_date=20240121T193110, end_date=20240121T193110
[2024-01-21T11:31:10.918-0800] {local_task_job.py:212} INFO - Task exited with return code 0
[2024-01-21T11:31:10.936-0800] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
