[2024-01-20T14:23:53.125-0800] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: python_pipeline.grouped_by_smoker manual__2024-01-20T22:23:45.310663+00:00 [queued]>
[2024-01-20T14:23:53.133-0800] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: python_pipeline.grouped_by_smoker manual__2024-01-20T22:23:45.310663+00:00 [queued]>
[2024-01-20T14:23:53.133-0800] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2024-01-20T14:23:53.133-0800] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2024-01-20T14:23:53.133-0800] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2024-01-20T14:23:53.155-0800] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): grouped_by_smoker> on 2024-01-20 22:23:45.310663+00:00
[2024-01-20T14:23:53.158-0800] {standard_task_runner.py:55} INFO - Started process 20732 to run task
[2024-01-20T14:23:53.160-0800] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'python_pipeline', 'grouped_by_smoker', 'manual__2024-01-20T22:23:45.310663+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/executing_python_pipeline.py', '--cfg-path', '/tmp/tmp4q95yw5p']
[2024-01-20T14:23:53.161-0800] {standard_task_runner.py:83} INFO - Job 57: Subtask grouped_by_smoker
[2024-01-20T14:23:53.208-0800] {task_command.py:389} INFO - Running <TaskInstance: python_pipeline.grouped_by_smoker manual__2024-01-20T22:23:45.310663+00:00 [running]> on host Mittu.
[2024-01-20T14:23:53.264-0800] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=madhu
AIRFLOW_CTX_DAG_ID=python_pipeline
AIRFLOW_CTX_TASK_ID=grouped_by_smoker
AIRFLOW_CTX_EXECUTION_DATE=2024-01-20T22:23:45.310663+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-20T22:23:45.310663+00:00
[2024-01-20T14:23:53.270-0800] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/mirukulla/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/mirukulla/airflow/dags/executing_python_pipeline.py", line 26, in groupby_smoke
    df = pd.read_json(json_data)
  File "/home/mirukulla/.local/lib/python3.10/site-packages/pandas/io/json/_json.py", line 791, in read_json
    json_reader = JsonReader(
  File "/home/mirukulla/.local/lib/python3.10/site-packages/pandas/io/json/_json.py", line 904, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/mirukulla/.local/lib/python3.10/site-packages/pandas/io/json/_json.py", line 944, in _get_data_from_filepath
    self.handles = get_handle(
  File "/home/mirukulla/.local/lib/python3.10/site-packages/pandas/io/common.py", line 728, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "/home/mirukulla/.local/lib/python3.10/site-packages/pandas/io/common.py", line 472, in _get_filepath_or_buffer
    raise ValueError(msg)
ValueError: Invalid file path or buffer object type: <class 'NoneType'>
[2024-01-20T14:23:53.273-0800] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=python_pipeline, task_id=grouped_by_smoker, execution_date=20240120T222345, start_date=20240120T222353, end_date=20240120T222353
[2024-01-20T14:23:53.290-0800] {standard_task_runner.py:100} ERROR - Failed to execute job 57 for task grouped_by_smoker (Invalid file path or buffer object type: <class 'NoneType'>; 20732)
[2024-01-20T14:23:53.333-0800] {local_task_job.py:212} INFO - Task exited with return code 1
[2024-01-20T14:23:53.344-0800] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
